# Generated by Django 6.1.1 on 2026-10-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('is_public_solution', models.BooleanField(default=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('is_editorial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Challenge submission',
                'verbose_name_plural': 'Challenge submissions',
                'db_table': 'challenge_submission',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('code', 'Code'), ('media', 'Media')], max_length=20)),
                ('asset_url', models.CharField(max_length=500)),
                ('asset_type', models.CharField(choices=[('challenge', 'Challenge Asset'), ('solution', 'Solution Code File')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='challenges.challenge')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='challenges.challengesubmission')),
            ],
            options={
                'verbose_name': 'Challenge asset',
                'verbose_name_plural': 'Challenge assets',
                'db_table': 'challenge_asset',
            },
        ),
    ]
