# Generated by Django 6.1.1 on 2026-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(editable=False, max_length=220, unique=True),
        ),
    ]
