# Generated by Django 6.1.1 on 2026-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeasset',
            name='path',
            field=models.CharField(default='.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='challengeasset',
            name='slug',
            field=models.SlugField(editable=False, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='slug',
            field=models.SlugField(editable=False, max_length=220, unique=True),
        ),
        migrations.AddConstraint(
            model_name='challengeasset',
            constraint=models.CheckConstraint(condition=models.Q(('challenge__isnull', False), ('submission__isnull', False), _connector='XOR'), name='asset_has_exactly_one_owner'),
        ),
    ]
