# Generated by Django 6.1.1 on 2026-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challengeasset_path_alter_challengeasset_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
